// Generated by Website Factory (GaLaBau vertical). Update via the factory pipeline, not by hand.

export type GalabauUnit = "qm" | "lfm" | "stk" | "pauschal";

export type GalabauServiceKey =
  | "gartenneugestaltung"
  | "pflasterarbeiten"
  | "terrassenbau"
  | "gartenpflege"
  | "zaun-sichtschutz"
  | "bewaesserung"
  | "baumpflege"
  | "gewerbeflaechen";

export type GalabauService = {
  key: GalabauServiceKey;
  slug: string;
  label: string;
  navLabel: string;
  cta: string;
  unit: GalabauUnit;
  teaser: string;
  intro: string;
  bullets: string[];
  ablauf: { title: string; text: string }[];
  faq: { q: string; a: string }[];
  image: string;
  estimate: { minPerUnit: number; maxPerUnit: number; baseMin: number };
  seo: { title: string; description: string };
};

export type GalabauBudgetBand = {
  id: string;
  label: string;
  min: number;
  max: number | null;
};

export type GalabauConfig = {
  company: {
    name: string;
    city: string;
    foundedYear: string;
    teamSize: string;
    machines: string;
  };
  claim: string;
  heroSubline: string;
  services: GalabauService[];
  serviceArea: {
    centerCity: string;
    radiusKm: number;
    note: string;
    plzPrefixes: string[];
    borderPlzPrefixes: string[];
    places: string[];
    /** Map centre from the Google profile. Without it the map is skipped. */
    center?: { lat: number; lng: number };
  };
  contact: {
    phone: string;
    phoneLink: string;
    whatsapp: string;
    whatsappLink: string;
    whatsappPrefill: string;
    email: string;
    leadEmail: string;
  };
  estimator: {
    enabled: boolean;
    minProjectEur: number;
    currency: string;
    roundingStep: number;
    disclaimer: string;
    sizeThresholds: { klein: number; mittel: number };
    surcharges: { hanglage: number; schwererZugang: number; rueckbauBestand: number };
    budgetBands: GalabauBudgetBand[];
    realismQuestion: string;
    realismOptions: { id: string; label: string }[];
  };
  recruiting: {
    enabled: boolean;
    headline: string;
    teaser: string;
    intro: string;
    roles: string[];
    benefits: string[];
  };
  trust: {
    seals: { label: string; note: string }[];
    usps: { label: string; text: string }[];
  };
  assistant: {
    enabled: boolean;
    photoUploadMaxFiles: number;
    photoUploadMaxMb: number;
    consentText: string;
    responsePromise: string;
  };
};

export const galabau: GalabauConfig = {
  "company": {
    "name": "Dienstleistungen Kurt",
    "city": "Forst",
    "foundedYear": "",
    "teamSize": "",
    "machines": ""
  },
  "claim": "Dienstleistungen Kurt - Garten- und Landschaftsbau in Forst",
  "heroSubline": "Gartengestaltung, Pflasterarbeiten, Baumpflege und Gartenpflege aus einem Betrieb. Einsatzgebiet: Forst, Bruchsal, Karlsruhe und rund 40 km Umkreis.",
  "services": [
    {
      "key": "gartenneugestaltung",
      "slug": "gartenneugestaltung",
      "label": "Gartenneugestaltung",
      "navLabel": "Gartengestaltung",
      "cta": "Projekt planen lassen",
      "unit": "qm",
      "teaser": "Vom leeren Grundstück oder alten Garten zur fertigen Anlage: Planung, Erdarbeiten, Wege, Beete, Rasen.",
      "intro": "Eine Gartenneugestaltung ist selten nur Bepflanzung. Meist hängen Rückbau, Erdarbeiten, Entwässerung, Wege und Terrasse mit drin. Wir nehmen das Grundstück in einem Zug auf, damit die Gewerke zusammenpassen und der Garten am Ende nicht aus Einzelteilen besteht. Bäume im Bestand beurteilen wir dabei gleich mit.",
      "bullets": [
        "Aufmaß vor Ort durch den Inhaber: Boden, Gefälle, Zufahrt",
        "Zwei bis drei Varianten statt einer einzigen Idee",
        "Erdarbeiten, Rückbau und Entsorgung des Aushubs",
        "Wege, Terrasse, Beete, Rasen und Begrünung aus einem Betrieb",
        "Bestandsbäume werden vor Baubeginn beurteilt, nicht danach"
      ],
      "ablauf": [
        {
          "title": "Anfrage",
          "text": "Sie schildern Fläche, Zustand und Wunsch über den Projekt-Assistenten, idealerweise mit Fotos."
        },
        {
          "title": "Termin vor Ort",
          "text": "Wir messen auf, prüfen Zugang, Boden und Gefälle und klären, was baulich sinnvoll ist."
        },
        {
          "title": "Planung & Angebot",
          "text": "Sie bekommen eine nachvollziehbare Planung mit Positionen, nicht nur eine Endsumme."
        },
        {
          "title": "Ausführung",
          "text": "Feste Bauzeit, ein Ansprechpartner, saubere Übergabe inklusive Pflegehinweisen."
        }
      ],
      "faq": [
        {
          "q": "Was kostet eine Gartenneugestaltung?",
          "a": "Das hängt stark von Fläche, Untergrund, Zugang und Material ab. Deshalb nennen wir online nur grobe Orientierungsrahmen und den verbindlichen Preis erst nach dem Aufmaß vor Ort."
        },
        {
          "q": "Wie lange dauert so ein Projekt?",
          "a": "Kleinere Umgestaltungen dauern wenige Tage, komplette Neuanlagen mit Erdarbeiten und Terrasse meist mehrere Wochen. Den Zeitrahmen legen wir vor Baubeginn fest."
        }
      ],
      "image": "/assets/leistungen/gartenneugestaltung-mit-beleuchtung.webp",
      "estimate": {
        "minPerUnit": 120,
        "maxPerUnit": 320,
        "baseMin": 4000
      },
      "seo": {
        "title": "Gartenneugestaltung in Forst | Dienstleistungen Kurt",
        "description": "Gartenneugestaltung mit Planung, Erdarbeiten, Wegen und Bepflanzung. Aufmaß vor Ort, klare Positionen, feste Bauzeit."
      }
    },
    {
      "key": "pflasterarbeiten",
      "slug": "pflasterarbeiten",
      "label": "Pflasterarbeiten",
      "navLabel": "Pflaster",
      "cta": "Fläche einschätzen lassen",
      "unit": "qm",
      "teaser": "Einfahrt, Wege und Hofflächen mit tragfähigem Unterbau und sauberer Entwässerung.",
      "intro": "Pflaster hält so lange, wie der Unterbau es zulässt. Wir bauen die Tragschicht auf die tatsächliche Belastung aus, planen das Gefälle mit und klären die Entwässerung, bevor der erste Stein liegt. In der Rheinebene um Forst steht häufig Sand oder Lehm an, das entscheidet über den Aufbau.",
      "bullets": [
        "Einfahrt, Zufahrt, Wege, Hof und Terrassenflächen",
        "Unterbau nach Belastung: PKW, Wohnmobil oder Lieferverkehr",
        "Entwässerung, Rinnen und Anschluss an Bestandsflächen",
        "Randeinfassungen, Naturstein und Betonstein, auch im Verband",
        "Bestandsflächen nehmen wir auf und entsorgen den Bruch"
      ],
      "ablauf": [
        {
          "title": "Fläche melden",
          "text": "Quadratmeter grob schätzen oder Fotos schicken, wir rechnen die Fläche nach."
        },
        {
          "title": "Aufbau festlegen",
          "text": "Wir klären Belastung, Untergrund und Entwässerung und wählen den passenden Aufbau."
        },
        {
          "title": "Angebot",
          "text": "Positionen für Aushub, Entsorgung, Tragschicht, Material und Einbau, getrennt ausgewiesen."
        },
        {
          "title": "Einbau",
          "text": "Aushub, Verdichtung, Verlegung, Abrütteln und Verfugen mit sauberer Baustellenübergabe."
        }
      ],
      "faq": [
        {
          "q": "Muss die alte Fläche raus?",
          "a": "Meist ja. Ein neues Pflaster auf altem, gesetztem Unterbau bekommt früher oder später Spurrillen. Wir prüfen den Bestand und sagen offen, ob ein Rückbau nötig ist."
        },
        {
          "q": "Wie viel Gefälle braucht die Fläche?",
          "a": "Als Faustwert rund zwei Prozent, weg vom Gebäude. Wo das nicht geht, planen wir Rinnen oder Versickerung ein."
        }
      ],
      "image": "/assets/leistungen/pflasterarbeiten-terrasse.webp",
      "estimate": {
        "minPerUnit": 90,
        "maxPerUnit": 210,
        "baseMin": 3000
      },
      "seo": {
        "title": "Pflasterarbeiten in Forst | Dienstleistungen Kurt",
        "description": "Pflasterarbeiten für Einfahrt, Wege und Hofflächen: tragfähiger Unterbau, geplante Entwässerung, saubere Randeinfassung."
      }
    },
    {
      "key": "terrassenbau",
      "slug": "terrassenbau",
      "label": "Terrassenbau",
      "navLabel": "Terrasse",
      "cta": "Terrasse anfragen",
      "unit": "qm",
      "teaser": "Terrassen aus Naturstein, Keramik oder Holz, inklusive Unterbau, Sichtschutz und Beleuchtung.",
      "intro": "Die Terrasse ist der Teil des Gartens, der täglich benutzt wird. Wie sie nach fünf Jahren aussieht, entscheiden Untergrund, Entwässerung und Materialwahl, nicht das Muster im Prospekt. Wir klären zuerst die Anschlusshöhe an der Tür, daran scheitern die meisten nachträglichen Lösungen.",
      "bullets": [
        "Materialien: Keramik, Naturstein, Betonplatten, Holz und WPC",
        "Unterbau: Splittbett, Stelzlager oder Punktfundamente",
        "Übergang zu Rasen, Beet und Sichtschutz wird mitgeplant",
        "Leerrohre und Leitungen liegen, bevor der Belag kommt",
        "Pflegehinweise je nach Material bei der Übergabe"
      ],
      "ablauf": [
        {
          "title": "Wunsch klären",
          "text": "Größe, Nutzung, Sonne und gewünschtes Material, gern mit Inspirationsbildern."
        },
        {
          "title": "Untergrund prüfen",
          "text": "Wir schauen uns Anschlusshöhen, Türschwellen und Entwässerung vor Ort an."
        },
        {
          "title": "Angebot",
          "text": "Aufbau, Material und Zusatzleistungen wie Beleuchtung getrennt kalkuliert."
        },
        {
          "title": "Bau",
          "text": "Unterbau, Belag, Randabschluss, Reinigung und Übergabe."
        }
      ],
      "faq": [
        {
          "q": "Holz oder Keramik?",
          "a": "Holz ist warm und lebendig, braucht aber Pflege. Keramik und Naturstein sind pflegeleicht und farbstabil. Wir zeigen beides an realen Flächen, bevor Sie sich festlegen."
        },
        {
          "q": "Geht das auch auf einer bestehenden Platte?",
          "a": "Oft ja, mit Stelzlagern. Voraussetzung ist eine ausreichende Aufbauhöhe an der Tür und ein funktionierendes Gefälle."
        }
      ],
      "image": "/assets/leistungen/terrassenbau-grossformatplatten-01.webp",
      "estimate": {
        "minPerUnit": 140,
        "maxPerUnit": 380,
        "baseMin": 3500
      },
      "seo": {
        "title": "Terrassenbau in Forst | Dienstleistungen Kurt",
        "description": "Terrassenbau mit Naturstein, Keramik oder Holz: geplanter Unterbau, Entwässerung, Sichtschutz und Beleuchtung."
      }
    },
    {
      "key": "gartenpflege",
      "slug": "gartenpflege",
      "label": "Gartenpflege",
      "navLabel": "Pflege",
      "cta": "Pflege anfragen",
      "unit": "qm",
      "teaser": "Einmalige Pflege oder fester Pflegevertrag: Rasen, Hecken, Beete und Saisonarbeiten.",
      "intro": "Pflege ist planbar. Wer feste Termine hat, spart sich den jährlichen Rückschnitt-Notfall. Wir machen beides: den einmaligen Einsatz, wenn der Garten über den Kopf gewachsen ist, und die feste Pflege über die Saison. Das Schnittgut nehmen wir mit, der Platz ist am Abend sauber.",
      "bullets": [
        "Einmalpflege für verwilderte Gärten inklusive Entsorgung",
        "Pflegevertrag mit festen Terminen über die Saison",
        "Rasenpflege: Mähen, Vertikutieren, Nachsaat, Düngung",
        "Heckenschnitt, Formschnitt und Rückschnitt von Sträuchern",
        "Laub und Frühjahrsputz, Winterdienst auf Anfrage"
      ],
      "ablauf": [
        {
          "title": "Bestand ansehen",
          "text": "Fotos oder Ortstermin, damit der Aufwand realistisch eingeschätzt wird."
        },
        {
          "title": "Umfang festlegen",
          "text": "Einmalig oder Vertrag, mit klarer Liste, was enthalten ist."
        },
        {
          "title": "Termine",
          "text": "Feste Turnusse statt Zufall, Sie wissen wann wir kommen."
        },
        {
          "title": "Pflege",
          "text": "Ausführung inklusive Abtransport des Schnittguts."
        }
      ],
      "faq": [
        {
          "q": "Was kostet ein Pflegevertrag?",
          "a": "Das richtet sich nach Fläche, Heckenlänge und Turnus. Nach einem kurzen Blick auf die Fläche nennen wir einen festen Jahresbetrag."
        },
        {
          "q": "Wann wird die Hecke geschnitten?",
          "a": "Der Formschnitt erfolgt außerhalb der gesetzlichen Schonzeit. Radikale Rückschnitte sind vom 1. März bis 30. September nicht zulässig."
        }
      ],
      "image": "/assets/leistungen/gartenpflege-heckenschnitt.webp",
      "estimate": {
        "minPerUnit": 3,
        "maxPerUnit": 12,
        "baseMin": 350
      },
      "seo": {
        "title": "Gartenpflege in Forst | Dienstleistungen Kurt",
        "description": "Gartenpflege als Einmalpflege oder Pflegevertrag: Rasen, Heckenschnitt, Beete und Saisonarbeiten mit festen Terminen."
      }
    },
    {
      "key": "zaun-sichtschutz",
      "slug": "zaun-sichtschutz",
      "label": "Zaun & Sichtschutz",
      "navLabel": "Zaun",
      "cta": "Sichtschutz anfragen",
      "unit": "lfm",
      "teaser": "Zäune, Sichtschutzwände und Gabionen, kalkuliert nach laufenden Metern.",
      "intro": "Zaun und Sichtschutz rechnen sich nach laufenden Metern. Entscheidend sind Höhe, Fundament und der genaue Grenzverlauf. Wir sagen vorab, wo eine Abstimmung mit dem Nachbarn oder der Gemeinde nötig ist, statt die Diskussion nach der Montage zu führen.",
      "bullets": [
        "Doppelstabmatten, Holz, WPC, Aluminium und Gabionen",
        "Kalkulation nach laufenden Metern inklusive Pfosten und Fundament",
        "Hinweise zu Grenzbebauung, Höhe und örtlichen Satzungen",
        "Tore und Türen mit passender Beschlagtechnik",
        "Alte Zäune bauen wir zurück und entsorgen sie"
      ],
      "ablauf": [
        {
          "title": "Meter schätzen",
          "text": "Grobe Länge und gewünschte Höhe genügen für die erste Einordnung."
        },
        {
          "title": "Grenze klären",
          "text": "Wir prüfen Verlauf, Untergrund und ob eine Genehmigung nötig ist."
        },
        {
          "title": "Angebot",
          "text": "Material, Pfosten, Fundamente und Tore als getrennte Positionen."
        },
        {
          "title": "Montage",
          "text": "Fundamente setzen, ausrichten, montieren, Baustelle räumen."
        }
      ],
      "faq": [
        {
          "q": "Wie hoch darf der Sichtschutz sein?",
          "a": "Das regeln Landesrecht und örtliche Satzung, häufig sind an der Grenze rund 1,80 m ohne Genehmigung möglich. Wir prüfen den konkreten Fall vor der Montage."
        },
        {
          "q": "Brauche ich Fundamente?",
          "a": "Bei Sichtschutzwänden und Toren ja. Bei leichten Zäunen genügen oft Einschlaghülsen, das entscheidet der Untergrund."
        }
      ],
      "image": "/assets/leistungen/zaun-und-sichtschutz.webp",
      "estimate": {
        "minPerUnit": 90,
        "maxPerUnit": 320,
        "baseMin": 1200
      },
      "seo": {
        "title": "Zaun & Sichtschutz in Forst | Dienstleistungen Kurt",
        "description": "Zaun und Sichtschutz nach laufenden Metern: Doppelstabmatten, Holz, Gabionen, mit Fundament und Hinweisen zur Genehmigung."
      }
    },
    {
      "key": "baumpflege",
      "slug": "baumpflege",
      "label": "Baumpflege",
      "navLabel": "Baumpflege",
      "cta": "Baum beurteilen lassen",
      "unit": "stk",
      "teaser": "Kronenpflege, Rückschnitt und Fällung, beurteilt am Baum statt nach Foto.",
      "intro": "Ein Baum wird nicht nach Gefühl geschnitten. Was weg darf, hängt von Art, Alter, Standort und Zustand ab, und ein falscher Schnitt lässt sich nicht zurücknehmen. Wir sehen uns den Baum vor Ort an und sagen, ob Pflege reicht oder ob mehr nötig ist.",
      "bullets": [
        "Kronenpflege, Auslichtung und Entnahme von Totholz",
        "Rückschnitt an Haus, Leitung und Grundstücksgrenze",
        "Fällung auch bei engem Stand, Abtransport inklusive",
        "Beurteilung von Standsicherheit und Schäden am Stamm",
        "Bodenverbesserung im Wurzelbereich geschwächter Bäume"
      ],
      "ablauf": [
        {
          "title": "Foto schicken",
          "text": "Ein Bild vom ganzen Baum und eines vom Stammfuß reichen für die erste Einschätzung."
        },
        {
          "title": "Beurteilung vor Ort",
          "text": "Wir prüfen Art, Zustand und Umfeld und klären, wie wir an den Baum herankommen."
        },
        {
          "title": "Angebot",
          "text": "Schnittumfang, Sicherung, Abtransport und Entsorgung getrennt ausgewiesen."
        },
        {
          "title": "Ausführung",
          "text": "Schnitt oder Fällung, Häckseln und Abfuhr, die Fläche wird besenrein übergeben."
        }
      ],
      "faq": [
        {
          "q": "Darf ich meinen Baum einfach fällen lassen?",
          "a": "Nicht überall. Viele Gemeinden haben eine Baumschutzsatzung, und zwischen dem 1. März und dem 30. September schützt das Bundesnaturschutzgesetz Gehölze zusätzlich. Wir prüfen Ihren Fall vor dem Termin und sagen Ihnen, ob ein Antrag nötig ist."
        },
        {
          "q": "Was kostet eine Fällung?",
          "a": "Das hängt von Höhe, Stand und Zugang ab. Ein frei stehender Baum auf der Wiese ist etwas anderes als einer zwischen Haus und Leitung. Den Preis nennen wir nach der Beurteilung vor Ort."
        }
      ],
      "image": "/assets/leistungen/baumpflege-klettertechnik.webp",
      "estimate": {
        "minPerUnit": 150,
        "maxPerUnit": 900,
        "baseMin": 450
      },
      "seo": {
        "title": "Baumpflege in Forst | Dienstleistungen Kurt",
        "description": "Baumpflege in Forst und Umgebung: Kronenpflege, Totholzentnahme, Rückschnitt und Fällung mit Beurteilung vor Ort."
      }
    }
  ],
  "serviceArea": {
    "centerCity": "Forst",
    "radiusKm": 40,
    "note": "Wir arbeiten im Umkreis von rund 40 km um Forst, von Karlsruhe bis Speyer und von Philippsburg bis Bretten. Liegt Ihr Projekt außerhalb, sagen wir Ihnen ehrlich, ob sich die Anfahrt für den Umfang rechnet.",
    "plzPrefixes": [
      "76",
      "68"
    ],
    "borderPlzPrefixes": [
      "69",
      "75",
      "67"
    ],
    "places": [
      "Forst",
      "Hambrücken",
      "Bruchsal",
      "Karlsdorf-Neuthard",
      "Ubstadt-Weiher",
      "Bad Schönborn",
      "Kronau",
      "Östringen",
      "Waghäusel",
      "Graben-Neudorf",
      "Philippsburg",
      "Bretten"
    ],
    "center": {
      "lat": 49.1548511,
      "lng": 8.5859768
    }
  },
  "contact": {
    "phone": "0176 43334808",
    "phoneLink": "tel:+4917643334808",
    "whatsapp": "0176 43334808",
    "whatsappLink": "https://wa.me/4917643334808",
    "whatsappPrefill": "Hallo Dienstleistungen Kurt, ich habe eine Frage zu einem Gartenprojekt in ",
    "email": "",
    "leadEmail": ""
  },
  "estimator": {
    "enabled": true,
    "minProjectEur": 2500,
    "currency": "EUR",
    "roundingStep": 500,
    "disclaimer": "Alle Angaben sind eine unverbindliche Orientierung, kein Angebot. Der tatsächliche Preis hängt von Boden, Unterbau, Zugang, Entwässerung, Material und Ausführung ab und steht erst nach dem Aufmaß vor Ort fest.",
    "sizeThresholds": {
      "klein": 5000,
      "mittel": 20000
    },
    "surcharges": {
      "hanglage": 0.15,
      "schwererZugang": 0.12,
      "rueckbauBestand": 0.1
    },
    "budgetBands": [
      {
        "id": "bis-5k",
        "label": "bis 5.000 €",
        "min": 0,
        "max": 5000
      },
      {
        "id": "5-15k",
        "label": "5.000 – 15.000 €",
        "min": 5000,
        "max": 15000
      },
      {
        "id": "15-30k",
        "label": "15.000 – 30.000 €",
        "min": 15000,
        "max": 30000
      },
      {
        "id": "30-60k",
        "label": "30.000 – 60.000 €",
        "min": 30000,
        "max": 60000
      },
      {
        "id": "ab-60k",
        "label": "mehr als 60.000 €",
        "min": 60000,
        "max": null
      },
      {
        "id": "unklar",
        "label": "Noch unklar",
        "min": 0,
        "max": null
      }
    ],
    "realismQuestion": "Wäre dieser grobe Rahmen für Sie grundsätzlich realistisch?",
    "realismOptions": [
      {
        "id": "passt",
        "label": "Ja, das passt so"
      },
      {
        "id": "guenstiger",
        "label": "Überraschend günstig"
      },
      {
        "id": "zu-hoch",
        "label": "Zu hoch"
      },
      {
        "id": "unklar",
        "label": "Noch unklar"
      }
    ]
  },
  "recruiting": {
    "enabled": true,
    "headline": "Landschaftsgärtner, Pflasterer oder Quereinsteiger?",
    "teaser": "In 60 Sekunden bewerben. Ohne Lebenslauf, ohne Anschreiben.",
    "intro": "Wir sind ein kleiner Betrieb aus Forst und arbeiten auf Baustellen zwischen Bruchsal, Karlsruhe und der Rheinebene. Wenn Sie anpacken können, sagen Sie uns kurz, was Sie schon gemacht haben. Den Rest klären wir am Telefon.",
    "roles": [
      "Landschaftsgärtner/in",
      "Pflasterer/in",
      "Helfer/in Garten- und Landschaftsbau",
      "Quereinsteiger/in"
    ],
    "benefits": [
      "Baustellen im Umkreis, abends sind Sie zu Hause",
      "Kleines Team, Absprachen laufen direkt mit dem Chef",
      "Abwechslung zwischen Pflaster, Grünflächen und Baumpflege",
      "Pünktliche Bezahlung, Überstunden werden erfasst"
    ]
  },
  "trust": {
    "seals": [],
    "usps": [
      {
        "label": "Der Inhaber nimmt auf",
        "text": "Der Inhaber misst selbst auf und bleibt bis zur Übergabe Ihr Ansprechpartner."
      },
      {
        "label": "Rund um Haus und Garten",
        "text": "Einfahrt, Grünflächen, Zaun und Baumschnitt laufen über denselben Betrieb."
      },
      {
        "label": "Auch samstags erreichbar",
        "text": "Werktags bis 19 Uhr, samstags bis 16 Uhr. Für Rückfragen genügt eine WhatsApp."
      }
    ]
  },
  "assistant": {
    "enabled": true,
    "photoUploadMaxFiles": 6,
    "photoUploadMaxMb": 8,
    "consentText": "Ich bin damit einverstanden, dass meine Angaben zur Bearbeitung meiner Anfrage gespeichert und verarbeitet werden. Die Daten werden nicht an Dritte weitergegeben.",
    "responsePromise": "Wir melden uns in der Regel innerhalb von 24 Stunden an Werktagen."
  }
};

export function findService(slug: string): GalabauService | undefined {
  return galabau.services.find((service) => service.slug === slug);
}

export default galabau;
